# site settings
title: Robin Axel Andrade Perez
subtitle: Computer Science Engineer
email: axelinw112@gmail.com
description: Soy un estudiante de ciencias computacionales de la UDG y me apasiona la inteligencia artificial.
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Morelos
city: Zapotlanejo
state: Jal
zip_code: 45430
country: Mexico
phone: (52) 3320450689

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/AxelinS
  LinkedIn: https://www.linkedin.com/in/robin-axel-andrade-perez-87b071168/
  Twitter: https://twitter.com/AxelinS

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
